/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

public class App {
    public static void main(String[] args) {
    	
    	//Write a Main class that creates a Button and then commands it to switch on and off. 
    	System.out.println("Create a Button and then command it to switch on and off.");
    	Switches b = new Button();
    	b.switchOn();
    	b.switchOff();
    	
    	//Write a Main class that creates a table lamp and then commands it to switch on and off.
    	System.out.println("\nCreates a table lamp and then command it to switch on and off.");
    	Lightbulb l = new Lightbulb();
    	Switches b2 = new Button(l); //This is the table lamp created, with a button connected to a lightbulb
    	b2.switchOn();
    	b2.switchOff();
    	
    	System.out.println("\nChanging Button, Same Lightbulb");
    	Switches b3 = new Button(l);
    	b3.switchOn();
    	b3.switchOff();
    	
    	System.out.println("\nChanging Lightbulb, Same Button");
    	Lightbulb l2 = new Lightbulb();
    	b3 = new Button(l2);
    	b3.switchOn();
    	b3.switchOff();
    	
    	//Replace the Button with a PushdownButton
    	System.out.println("\nReplace the Button with a PushdownButton");
    	b3 = new PushdownButton(l); //This is the table lamp created, with a button connected to a lightbulb
    	b3.pushButton();
    	b3.pushButton();
    	b3.pushButton();
    	
    }
}
