/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

import org.junit.jupiter.api.Test;

import edu.iit.cs445.spring22.LightSource.*;
import edu.iit.cs445.spring22.Switch.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	@Test
	void buttonStartsOff() {
		System.out.println("\nbuttonStartsOff");
    	Switches b = new Button();
    	assertEquals(false, b.getIsSwitchOn());
    }
	@Test
	void lightbulbStartsOff() {
		System.out.println("\nlightbulbStartsOff");
		Lightbulb l = new Lightbulb();
    	assertEquals(false, l.getLightSourceOn());
    }
	@Test
	void pushdownButtonStartsOff() {
		System.out.println("\npushdownButtonStartsOff");
    	Switches b = new PushdownButton();
    	assertEquals(false, b.getIsSwitchOn());
    }
	
	@Test
	void buttonStartsOffwithLightbulb() {
		System.out.println("\nbuttonStartsOff");
		Lightbulb l = new Lightbulb();
    	Switches b = new Button(l);
    	assertEquals(false, b.getIsSwitchOn());
    }
	@Test
	void pushdownButtonStartsOffwithLightbulb() {
		System.out.println("\npushdownButtonStartsOff");
		Lightbulb l = new Lightbulb();
    	Switches b = new PushdownButton(l);
    	assertEquals(false, b.getIsSwitchOn());
    }
	@Test
	void lightbulbStartsOffwihtButton() {
		System.out.println("\nlightbulbStartsOff");
		Lightbulb l = new Lightbulb();
		Switches b = new Button(l);
    	assertEquals(false, l.getLightSourceOn());
    }
	@Test
	void lightbulbStartsOffwihtPushdownButton() {
		System.out.println("\nlightbulbStartsOff");
		Lightbulb l = new Lightbulb();
		Switches b = new PushdownButton(l);
    	assertEquals(false, l.getLightSourceOn());
    }
	
	@Test
	void buttonSwitchesOn() {
		System.out.println("\nbuttonSwitchesOn");
    	Switches b = new Button();
    	b.switchOn();
    	assertEquals(true, b.getIsSwitchOn());
    }
	@Test
	void buttonSwitchesOff() {
		System.out.println("\nbuttonSwitchesOff");
    	Switches b = new Button();
    	b.switchOff();
    	assertEquals(false, b.getIsSwitchOn());
    }
	
	@Test
	void lightbulbOn() {
		System.out.println("\nlightbulbOn");
    	Lightbulb l = new Lightbulb();
    	l.on();
    	assertEquals(true, l.getLightSourceOn());
    }
	@Test
	void lightbulbOff() {
		System.out.println("\nlightbulbOff");
		Lightbulb l = new Lightbulb();
    	l.off();
    	assertEquals(false, l.getLightSourceOn());
    }
	
	@Test
	void buttonTurnsOnLightBulb() {
		System.out.println("\nbuttonTurnsOnLightBulb");
		Lightbulb l = new Lightbulb();
    	Switches b = new Button(l);
    	b.switchOn();
    	assertEquals(true, l.getLightSourceOn());
    }
	@Test
	void buttonTurnsOffLightBulb() {
		System.out.println("\nbuttonTurnsOffLightBulb");
		Lightbulb l = new Lightbulb();
    	Switches b = new Button(l);
    	b.switchOff();
    	assertEquals(false, l.getLightSourceOn());
    }
	
	@Test
	void pushButtonToOn() {
		System.out.println("\npushButtonToOn");
    	Switches b = new PushdownButton();
    	b.pushButton();
    	assertEquals(true, b.getIsSwitchOn());
    }
	@Test
	void pushButtonToOff() {
		System.out.println("\npushButtonToOff");
    	Switches b = new PushdownButton();
    	b.pushButton();//Turn on
    	b.pushButton();//Turn off
    	assertEquals(false, b.getIsSwitchOn());
    }
	
	@Test
	void pushButtonTurnsLightbulbOn() {
		System.out.println("\npushButtonTurnsLightbulbOn");
		Lightbulb l = new Lightbulb();
		Switches b = new PushdownButton(l);
    	b.pushButton();
    	assertEquals(true, b.getIsSwitchOn());
    }
	@Test
	void pushButtonTurnsLightbulbOff() {
		System.out.println("\npushButtonTurnsLightbulbOff");
		Lightbulb l = new Lightbulb();
		Switches b = new PushdownButton(l);
    	b.pushButton();//Turn on
    	b.pushButton();//Turn off
    	assertEquals(false, b.getIsSwitchOn());
    }
	
}
